import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";

import { apiPatch, useApi } from "../api";
import { ConfidenceBadge, EvidenceIds } from "../components/DataDisplay";
import { Pagination } from "../components/Pagination";
import { StatePanel } from "../components/StatePanel";
import { label } from "../format";
import { ISSUE_FAMILIES } from "../types";
import type { Page, ReviewDecision, ReviewItem } from "../types";

const PAGE_SIZE = 100;

function ReviewList({ data }: { data: { reviews: ReviewItem[]; activeId: string | null; select: (id: string) => void } }) {
  return <div className="review-list">{data.reviews.map((review) => (
    <button type="button" aria-label={`Review ${review.review_id}, ${label(review.incident.issue_family)}`} aria-pressed={data.activeId === review.review_id} className={data.activeId === review.review_id ? "active" : ""} key={review.review_id} onClick={() => data.select(review.review_id)}>
      <span className="review-state">{review.decision.slice(0, 1)}</span><div><strong>{label(review.incident.issue_family)}</strong><small>{review.incident.asset_key}</small><code>{review.incident.incident_id}</code></div><ConfidenceBadge value={review.incident.confidence} level={review.incident.confidence_level} />
    </button>
  ))}</div>;
}

interface ReviewActionData {
  item: ReviewItem;
  note: string;
  setNote: (note: string) => void;
  issueFamily: string;
  setIssueFamily: (issueFamily: string) => void;
  recommendation: string;
  setRecommendation: (recommendation: string) => void;
  submit: (decision: ReviewDecision) => Promise<void>;
  submitting: boolean;
  message: string | null;
}

function ReviewAction({ data }: { data: ReviewActionData }) {
  const insight = data.item.insight;
  const rejected = data.item.decision === "REJECTED";
  const issueFamilies = Array.from(new Set([data.issueFamily, ...ISSUE_FAMILIES]));
  return (
    <div className="review-action reveal">
      {rejected && <section className="rejection-banner"><strong>HUMAN REVIEW: REJECTED</strong><span>This finding is retained for audit and excluded from operational metrics.</span></section>}
      <div className="review-action-head">
        <div><span>REVIEW ITEM / {data.item.review_id}</span><h2>{insight.title}</h2><small className="provenance-line">Generated by {insight.generated_by}{insight.human_override ? " / human override active" : " / no human override"}</small></div>
        <ConfidenceBadge value={insight.confidence} level={insight.confidence_level} />
      </div>
      <section className="review-comparison">
        <article><span>OBSERVATION</span>{insight.observations.length ? insight.observations.map((item) => <p key={item}>{item}</p>) : <p className="muted-copy">No observation text returned.</p>}</article>
        <article><span>MODEL INTERPRETATION</span><p>{insight.interpretation}</p></article>
        <article><span>{rejected ? "REJECTED ACTION / AUDIT ONLY" : "MODEL PROPOSAL"}</span><p>{insight.recommended_action}</p></article>
      </section>
      <section className="citation-check"><strong>Citation set</strong><EvidenceIds identifiers={insight.supporting_work_orders} /><Link to={`/investigations/${insight.incident_id}`}>Inspect source timeline -&gt;</Link></section>
      <section className="review-edit-grid" aria-label="Review edits">
        <label className="review-field">Issue family<select aria-label="Edit issue family" value={data.issueFamily} onChange={(event) => data.setIssueFamily(event.target.value)}>{issueFamilies.map((family) => <option value={family} key={family}>{label(family)}</option>)}</select><small>Changing this reclassifies the incident and applies its rule.</small></label>
        <label className="review-field">Recommendation<textarea aria-label="Edit recommendation" value={data.recommendation} maxLength={4000} onChange={(event) => data.setRecommendation(event.target.value)} placeholder="Enter an authorized next step or leave the generated action unchanged..." /><small>Stored as a human override when changed.</small></label>
      </section>
      <label className="review-note">Reviewer note<textarea value={data.note} maxLength={2000} onChange={(event) => data.setNote(event.target.value)} placeholder="Record evidence checked, corrections, or rejection rationale..." /></label>
      {data.message && <p className="form-message" role="alert">{data.message}</p>}
      <div className="review-controls"><button type="button" disabled={data.submitting} className="reject-button" onClick={() => data.submit("REJECTED")}>Reject + save</button><button type="button" disabled={data.submitting} className="hold-button" onClick={() => data.submit("PENDING")}>Hold + save</button><button type="button" disabled={data.submitting} className="confirm-button" onClick={() => data.submit("CONFIRMED")}>Confirm + save</button></div>
    </div>
  );
}

function ActiveReview({ data }: { data: { item: ReviewItem; reload: () => void } }) {
  const [note, setNote] = useState(data.item.reviewer_note ?? "");
  const [issueFamily, setIssueFamily] = useState(data.item.edited_issue_family ?? data.item.incident.issue_family);
  const [recommendation, setRecommendation] = useState(data.item.edited_recommendation ?? data.item.insight.recommended_action);
  const [submitting, setSubmitting] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const submit = async (decision: ReviewDecision) => {
    if (decision === "REJECTED" && !window.confirm("Reject this finding and remove it from operational outputs?")) return;
    setSubmitting(true); setMessage(null);
    const initialIssueFamily = data.item.edited_issue_family ?? data.item.insight.issue_family;
    const initialRecommendation = data.item.edited_recommendation ?? data.item.insight.recommended_action;
    const issueOverride = issueFamily !== initialIssueFamily ? issueFamily : data.item.edited_issue_family;
    const recommendationValue = recommendation.trim();
    const recommendationOverride = recommendationValue !== initialRecommendation
      ? recommendationValue || null
      : data.item.edited_recommendation;
    try {
      await apiPatch(`/reviews/${data.item.insight.insight_id}`, {
        decision,
        reviewer_note: note.trim() || null,
        edited_issue_family: issueOverride,
        edited_recommendation: recommendationOverride,
      });
      setMessage(`Decision saved as ${decision}.`); data.reload();
    } catch (error: unknown) {
      setMessage(`Update failed: ${error instanceof Error ? error.message : "The review could not be saved."}`);
    } finally {
      setSubmitting(false);
    }
  };
  return <ReviewAction data={{ item: data.item, note, setNote, issueFamily, setIssueFamily, recommendation, setRecommendation, submit, submitting, message }} />;
}

export function ReviewPage() {
  const [params, setParams] = useSearchParams();
  const selectedDecision = params.get("decision");
  const decision: ReviewDecision | "ALL" = selectedDecision === "CONFIRMED" || selectedDecision === "REJECTED" || selectedDecision === "ALL" ? selectedDecision : "PENDING";
  const requestedOffset = Number(params.get("offset") ?? 0);
  const offset = Number.isInteger(requestedOffset) && requestedOffset >= 0 ? requestedOffset : 0;
  const selectedReview = params.get("review");
  const selectedInsight = params.get("insight");
  const decisionQuery = decision === "ALL" ? "" : `&decision=${decision}`;
  const insightQuery = selectedInsight ? `&insight_id=${encodeURIComponent(selectedInsight)}` : "";
  const result = useApi<Page<ReviewItem>>(`/reviews?limit=${PAGE_SIZE}&offset=${offset}${decisionQuery}${insightQuery}`);
  const health = useApi<{ review_threshold: number }>("/health");
  useEffect(() => {
    if (result.data && offset >= result.data.total && offset > 0) {
      const lastPage = Math.max(0, Math.floor((result.data.total - 1) / PAGE_SIZE) * PAGE_SIZE);
      setParams(reviewParams(decision, lastPage), { replace: true });
    }
  }, [decision, offset, result.data, setParams]);
  if (result.loading && !result.data) return <StatePanel state="loading" />;
  if (result.error) return <StatePanel state="error" message={result.error} retry={result.reload} />;
  const reviews = result.data?.items ?? [];
  const active = reviews.find((review) => review.review_id === selectedReview) ?? reviews[0];
  const threshold = health.data ? `${Math.round(health.data.review_threshold * 100)}%` : "configured";
  const chooseDecision = (value: ReviewDecision | "ALL") => setParams(reviewParams(value, 0));
  const setOffset = (value: number) => setParams(reviewParams(decision, value));
  const selectReview = (reviewId: string) => setParams(reviewParams(decision, offset, reviewId));
  return <div className="page-stack reveal"><section className="page-title"><div><span className="eyebrow">HUMAN-IN-THE-LOOP</span><h1>Review Queue</h1></div><p><strong>{result.data?.total ?? 0}</strong> {decision.toLowerCase()} findings under the {threshold} review policy</p></section><div className="list-tools"><label>Decision<select value={decision} onChange={(event) => chooseDecision(event.target.value as ReviewDecision | "ALL")}><option value="PENDING">Pending</option><option value="CONFIRMED">Confirmed</option><option value="REJECTED">Rejected</option><option value="ALL">All records</option></select></label>{result.data && <Pagination data={{ ...result.data, setOffset }} />}</div><div className="review-layout"><aside className="review-register"><div className="register-head"><strong>LOW CONFIDENCE FIRST</strong><span>{result.data?.total ?? 0}</span></div><ReviewList data={{ reviews, activeId: active?.review_id ?? null, select: selectReview }} /></aside><section className="panel review-detail">{active ? <ActiveReview key={active.review_id} data={{ item: active, reload: result.reload }} /> : <StatePanel state="empty" message="No findings match this decision view." />}</section></div></div>;
}

function reviewParams(decision: ReviewDecision | "ALL", offset: number, reviewId?: string): URLSearchParams {
  const params = new URLSearchParams({ decision, offset: String(offset) });
  if (reviewId) params.set("review", reviewId);
  return params;
}
